# Generated by Django 5.2.7 on 2025-11-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='method',
            field=models.CharField(default='cash', max_length=50),
            preserve_default=False,
        ),
    ]
