# Generated by Django 5.2.7 on 2025-11-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_transaction_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='provider',
            field=models.CharField(default='', max_length=50),
        ),
    ]
